blueprint:
  name: Bewegungsmelder Licht Automation
  description: "Schaltet ein Licht oder einen Schalter basierend auf einem Bewegungsmelder ein und aus. Mit automatischer Verlängerung bei erneuter Bewegung und optionaler Zeitsteuerung."
  source_url: https://github.com/rbrueckner82/homeassistant/edit/main/light_at_motion.yaml
